### ISSUE TITLE
你好，帮忙看下这段错误日志什么原因？

### ISSUE THREAD

**Issue by shiqinying** [Cherrison/CrackMinApp#15]
Decompile ./pages/group/group.wxml...
error on ./pages/group/group.wxml(Main)
err:  Error: Noticable generics content: [object Object]
    at analyze (D:\CrackMinApp-master\nodejs\nodejs\wuWxml.js:141:16)
    at anaRecursion (D:\CrackMinApp-master\nodejs\nodejs\wuWxml.js:11:10)
    at analyze (D:\CrackMinApp-master\nodejs\nodejs\wuWxml.js:217:6)
    at doWxml (D:\CrackMinApp-master\nodejs\nodejs\wuWxml.js:310:2)
    at tryWxml (D:\CrackMinApp-master\nodejs\nodejs\wuWxml.js:338:3)
    at z (D:\CrackMinApp-master\nodejs\nodejs\wuWxml.js:384:23)
    at z (D:\CrackMinApp-master\nodejs\nodejs\wuRestoreZ.js:244:17)
    at catchZGroup (D:\CrackMinApp-master\nodejs\nodejs\wuRestoreZ.js:15:2)
    at catchZ (D:\CrackMinApp-master\nodejs\nodejs\wuRestoreZ.js:19:29)
    at getZ (D:\CrackMinApp-master\nodejs\nodejs\wuRestoreZ.js:244:2)

**Comment by Cherrison** [comment]
### 是不是不全
我里面的demo可以运行吗?
