### ISSUE TITLE
Error: Cannot find module 'vm2'

### ISSUE THREAD

**Issue by zhmcoder** [Cherrison/CrackMinApp#8]
module.js:549
    throw err;
    ^

Error: Cannot find module 'vm2'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\CrackMinApp-master\nodejs\nodejs\wuConfig.js:5:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by Cherrison** [comment]
解压那个压缩包了嘛

**Comment by Cherrison** [comment]
解决了
